### ISSUE TITLE
TODO entro 30 Aprile

### ISSUE THREAD

**Issue by Giovanni-Michieletto** [Giovanni-Michieletto/TecWeb-Ricette#2]
- [x] Alt immagini  (Alice)
- [x] Colori  (Alice)
- [x] Meta  (Giovanni)
- [x] No css in html  (Giovanni)
- [x] No JavaScipt in Html  (Giovanni)
- [x] Immagini admin  (Giovanni)
- [x] Header mobile  (Simone)
- [x] Torna su interagibili con tastiera e colore fluttuante (Simone)
- [x] Card singolo  (Simone)
- [x] Pagina elimina  (Giovanni)
- [x] Pagina modifica  (Giovanni)
- [x] Galleria homa con php  (Giovanni)
- [x] Aggiustare php (Giovanni)
- [x] JavaScript form  (Francesco)
- [x] JavaScript Login  (Francesco)
- [x] login php (Giovanni)

**Chi ha finito**
- [x] Aiuti alla navigazione (Cosa oltra ai torna su?)
- [x] Footer generali da sistemare uguali (Giovanni)
- [x] Accessibilità Aria (Alice)
- [x] Logo barra indirizzi (Giovanni)
- [x] breadcrumb (Giovanni)

**Fine degli altri**
- [ ] Validazione html (https://github.com/Giovanni-Michieletto/TecWeb-Ricette/issues/6#issue-874401740)
- [x] Accessibilità tab, etc...
- [ ] Relazione (https://github.com/Giovanni-Michieletto/TecWeb-Ricette/issues/5#issue-874398304)
